/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.monitoramento.coldstock.telas;

import com.mycompany.monitoramento.coldstock.modelos.Consulta;
import com.mycompany.monitoramento.coldstock.modelos.Operacao;
import com.mycompany.monitoramento.coldstock.modelos.Imagem;
import com.mycompany.monitoramento.coldstock.modelos.Maquina;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class TelaEditarMaquina extends javax.swing.JFrame {

    List<Configuracao> carrinho = new ArrayList<>();

    /**
     * Creates new form telaEditarMaquina
     */
    // criamos objetos novamente
    Consulta objBD = new Consulta();
    //Imagem imagem = new Imagem();
    Integer idMaquina;
    String nomeMaquina;
    public TelaEditarMaquina() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#343C41"));
        ImageIcon imagem = new ImageIcon(getClass().getClassLoader().getResource("1601053028644.png"));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("1601053028644.png")));
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(imagem.retornarCaminho("/1601053028644.png")));
        jLabel6.setIcon(imagem);
        carregarComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbComponentes = new javax.swing.JTable();
        lblNomeMaquina = new java.awt.Label();
        cbEscolhaComponente = new javax.swing.JComboBox<>();
        btnAdicionarComponente = new javax.swing.JButton();
        txtCapacidadeMax = new javax.swing.JTextField();
        txtPorcentagemMax1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResumo = new javax.swing.JTextArea();
        btnLimpar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(Color.decode("#343C41"));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(31, 40, 45));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("COLD STOCK");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MONITORAMENTO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3))
        );

        btnCadastrar.setBackground(new java.awt.Color(77, 172, 166));
        btnCadastrar.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(77, 172, 166));
        btnEditar.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setMaximumSize(new java.awt.Dimension(131, 29));
        btnEditar.setMinimumSize(new java.awt.Dimension(131, 29));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(77, 172, 166));
        btnExcluir.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setMaximumSize(new java.awt.Dimension(131, 29));
        btnExcluir.setMinimumSize(new java.awt.Dimension(131, 29));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tbComponentes.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        tbComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COMPONENTE", "MÁXIMA", "PORCENTAGEM MAX"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    tbComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tbComponentesMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tbComponentes);

    lblNomeMaquina.setBackground(new java.awt.Color(31, 40, 45));
    lblNomeMaquina.setFont(new java.awt.Font("Montserrat", 1, 17)); // NOI18N
    lblNomeMaquina.setForeground(new java.awt.Color(255, 255, 255));
    lblNomeMaquina.setText("    Máquina 1");

    cbEscolhaComponente.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
    cbEscolhaComponente.setForeground(new java.awt.Color(153, 153, 153));
    cbEscolhaComponente.setToolTipText("-- escolha um componente--");
    cbEscolhaComponente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbEscolhaComponenteActionPerformed(evt);
        }
    });

    btnAdicionarComponente.setBackground(new java.awt.Color(77, 172, 166));
    btnAdicionarComponente.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
    btnAdicionarComponente.setForeground(new java.awt.Color(255, 255, 255));
    btnAdicionarComponente.setText("+");
    btnAdicionarComponente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 172, 166), 1, true));
    btnAdicionarComponente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAdicionarComponenteActionPerformed(evt);
        }
    });

    txtCapacidadeMax.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtCapacidadeMaxKeyReleased(evt);
        }
    });

    txtPorcentagemMax1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtPorcentagemMax1ActionPerformed(evt);
        }
    });
    txtPorcentagemMax1.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtPorcentagemMax1KeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtPorcentagemMax1KeyReleased(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Montserrat", 1, 11)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Escolha um componente");

    jLabel2.setFont(new java.awt.Font("Montserrat", 1, 11)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Insira uma máxima");

    jLabel3.setFont(new java.awt.Font("Montserrat", 1, 11)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Insira a porcentagem máxima");

    txtResumo.setEditable(false);
    txtResumo.setColumns(20);
    txtResumo.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
    txtResumo.setRows(5);
    txtResumo.setText("Itens adicionados: ");
    jScrollPane2.setViewportView(txtResumo);

    btnLimpar.setBackground(new java.awt.Color(77, 172, 166));
    btnLimpar.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
    btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
    btnLimpar.setText("Limpar Carrinho");
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimparActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(20, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnLimpar)
                    .addGap(30, 30, 30)
                    .addComponent(btnCadastrar)
                    .addGap(18, 18, 18)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNomeMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbEscolhaComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAdicionarComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtCapacidadeMax)
                        .addComponent(txtPorcentagemMax1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2))
                    .addContainerGap(19, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCadastrar)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLimpar))
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lblNomeMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbEscolhaComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdicionarComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addGap(2, 2, 2)
                    .addComponent(txtCapacidadeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPorcentagemMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(12, 24, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        new Operacao().editarComponentes(Integer.valueOf(txtPorcentagemMax1.getText()), Double.valueOf(txtCapacidadeMax.getText()), idMaquina, cbEscolhaComponente.getSelectedIndex() + 1);
        carregarTabela(Maquina.fkmaquina, nomeMaquina);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        new Operacao().excluirComponentes(Maquina.fkmaquina, cbEscolhaComponente.getSelectedIndex() + 1);
        carregarTabela(Maquina.fkmaquina, nomeMaquina);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbEscolhaComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaComponenteActionPerformed
        // TODO add your handling code here:
        txtCapacidadeMax.setText("");
        txtPorcentagemMax1.setText("");
    }//GEN-LAST:event_cbEscolhaComponenteActionPerformed

    private void txtPorcentagemMax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentagemMax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentagemMax1ActionPerformed


    private void btnAdicionarComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarComponenteActionPerformed
        if (txtCapacidadeMax.getText().trim().equals("") || txtPorcentagemMax1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Não pode conter caixas de textos vazios");
        } else {
            Configuracao novaConfiguracao = new Configuracao();

            novaConfiguracao.setComp(cbEscolhaComponente.getSelectedItem().toString());
            novaConfiguracao.setMaximaComponente(txtCapacidadeMax.getText());
            novaConfiguracao.setPorcentagem(txtPorcentagemMax1.getText());

            System.out.println(novaConfiguracao.getComp());
            System.out.println(novaConfiguracao.getMaximaComponente());
            System.out.println(novaConfiguracao.getPorcentagem());
            txtCapacidadeMax.setText("");
            txtPorcentagemMax1.setText("");
            carrinho.add(novaConfiguracao);

            String Frase = "Itens adicionados:\n ";

            for (Configuracao configuracao : carrinho) {

                Frase += configuracao.getComp() + ",";
                Frase += configuracao.getMaximaComponente() + ",";
                Frase += configuracao.getPorcentagem() + "\n";

                txtResumo.setText(Frase);
            }

        }
    }//GEN-LAST:event_btnAdicionarComponenteActionPerformed

    private void txtPorcentagemMax1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemMax1KeyReleased
        // TODO add your handling code here:
        // pegando o evento que está entrando na porcentagem e verificando se ele é um digito
        if (Character.isDigit(evt.getKeyChar())) {
            // verificando se a porcentagem é maior que 100. 
            if (Double.parseDouble(txtPorcentagemMax1.getText()) > 100) {
                txtPorcentagemMax1.setText("100");
            }
            // verificando se a porcentagem é menor que 0.
            if (Double.parseDouble(txtPorcentagemMax1.getText()) < 0) {
                txtPorcentagemMax1.setText("0");
            }
        } else {
            txtPorcentagemMax1.setText("");
        }
    }//GEN-LAST:event_txtPorcentagemMax1KeyReleased

    private void tbComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComponentesMouseClicked
        // TODO add your handling code here:
        // ao clickar em alguma coluna da tabela ele mudar o combobox para a 
        // os dois textos recebem um conteudos pro texto. 
        cbEscolhaComponente.setSelectedItem(String.valueOf(tbComponentes.getModel().getValueAt(tbComponentes.getSelectedRow(), 0)));
        txtCapacidadeMax.setText(String.valueOf(tbComponentes.getModel().getValueAt(tbComponentes.getSelectedRow(), 1)).split(" ")[0]);
        txtPorcentagemMax1.setText(String.valueOf(tbComponentes.getModel().getValueAt(tbComponentes.getSelectedRow(), 2)).split(" ")[0]);

    }//GEN-LAST:event_tbComponentesMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        // passando o txtResumo, como parametro para o separarCarrinho.
        separarCarrinho(txtResumo.getText());
        // Inserindo os componentes dentro do BD 
        new Operacao().inserirComponentes(Maquina.fkmaquina, cbEscolhaComponente.getSelectedIndex() + 1,
                tbComponentes, separarCarrinho(txtResumo.getText()));
        //Esvaziando o textArea;
        txtResumo.setText("Itens adicionados:\n ");
        //Reload da tabela
        carregarTabela(Maquina.fkmaquina, nomeMaquina);
        // Limpando o List carrinho;
        carrinho.clear();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        // Limpando o List carrinho;
        carrinho.clear();
        //Esvaziando o textArea;
        txtResumo.setText("Itens adicionados:\n ");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCapacidadeMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadeMaxKeyReleased
        // TODO add your handling code here:
        // Deixando apenas numeros passarem e o . 

    }//GEN-LAST:event_txtCapacidadeMaxKeyReleased

    private void txtPorcentagemMax1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentagemMax1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPorcentagemMax1KeyPressed
    private String[] separarCarrinho(String carrinhoItens) {
        // seperar o texto do textArea por quebra de linha '\n', e colocando em um array do tipo String
        String[] itens = carrinhoItens.split("\n");
        return itens;
    }

    /**
     * @param args the command line arguments
     */
    private void carregarComponentes() {
        try {
            // a logica é a mesma da tela anterior, onde populamos a combo box das maquinas
            objBD.conectar();
            ResultSet retornoBD = objBD.consultarComponentes();
            while (retornoBD.next()) {
                String nomeComponente = retornoBD.getString("nomeComponente");
                // na combo box, adicionamos o nome dos componentes
                cbEscolhaComponente.addItem(nomeComponente);
            }
        } catch (SQLException se) {
            System.out.println(se);
        }
        tbComponentes.setOpaque(true);
        tbComponentes.setFillsViewportHeight(true);
        tbComponentes.setBackground(Color.decode("#FFFFFF"));
    }

    public void carregarTabela(Integer idMaquina, String nomeMaquina) {
        this.idMaquina = idMaquina;
        this.nomeMaquina = nomeMaquina;
        try {
            objBD.conectar();
            ResultSet retornoBD = objBD.consultarConfiguracaoMaquina(idMaquina);
            lblNomeMaquina.setText(nomeMaquina);
            tbComponentes.removeAll();
            // aqui criamos um objeto de tabela, que ira popular nossa tbComponentes
            DefaultTableModel tabela = (DefaultTableModel) tbComponentes.getModel();
            //aqui deixamos o numero de linhas como 0, para poder reiniciar a tabela sempre que a tela for recarregada
            tabela.setRowCount(0);
            while (retornoBD.next()) {
                // aqui separamos as informações em variaveis
                String nomeComponente = retornoBD.getString("nomeComponente");
                String capacidadeMax = retornoBD.getString("capacidadeMax");
                String metrica = retornoBD.getString("metrica");
                String porcentagemMax = retornoBD.getString("porcentagemMax");
                // para cada proximo item da lista, nos adicionamos na lista as informações anteriores
                tabela.addRow(new Object[]{nomeComponente, capacidadeMax + " " + metrica, porcentagemMax + " %"});
            }
        } catch (SQLException se) {
            System.out.println(se);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaEditarMaquina().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarComponente;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbEscolhaComponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label lblNomeMaquina;
    private javax.swing.JTable tbComponentes;
    private javax.swing.JTextField txtCapacidadeMax;
    private javax.swing.JTextField txtPorcentagemMax1;
    private javax.swing.JTextArea txtResumo;
    // End of variables declaration//GEN-END:variables
}
